#!/bin/sh

USER=limesroeiennl
HOST=limesr.ssh.transip.me
DIR=/www/   # the directory where your website files should go

set -e

echo "Building site for production..."
hugo --environment production --minify

echo "Deploying to server..."
rsync -avz --delete public/ ${USER}@${HOST}:~/${DIR} # this will delete everything on the server that's not in the local public directory 

exit 0
